# This message contains interaction figure data send to the referee system

std_msgs/Header header


uint8[] figure_name			#size:3

uint32 operate_tpye			#default 3:delete
uint32 figure_tpye 			#default 3:ellipse

uint32 layer				#default 4
uint32 color	 			#default 4:purple

uint32 details_a			#default 9
uint32 details_b			#default 9

uint32 width				#default 10

uint32 start_x 				#default 11
uint32 start_y	 			#default 11

uint32 details_c 			#default 10
uint32 details_d 			#default 11
uint32 details_e			#default 11
